for i in range(...):
    for j in range(...):
        ...
    for k in range(...):
        ...
    for l in range(...):
        ...
for i in range(...):
    for j in range(...):
        ...
    for k in range(...):
        ...
    for l in range(...):
        ...
